# Generated by Django 4.2.3 on 2026-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scanexecution_scanresult_scanportresult_scaneventlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='executed_command',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='parser_validation_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='parser_warnings_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='raw_error_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
